### PR TITLE
added boilerplate.

### PR DESCRIPTION
**Pull request by ErnestoDLS**
Hey guys, just added the boilerplate for our project.

### CODE REVIEW

**Comment by jasonvanderslice** [comment]
I have concerns about this...

**Comment by Scott-McCann** [comment]
Care to elaborate there, jason?

**Comment by jasonvanderslice** [comment]
typing

This boilerplate has dependencies for: `sass`, `npm`, and very brittle on folder structure... there should be additions to the `readme.md` pointing out what is needed to make sure it's communicated how to build _front end_ assets

**Comment by jasonvanderslice** [comment]
[this might be good to add to this pr](https://github.com/tiy-sat/fee-boilerplate/blob/master/README.md)

**Comment by jasonvanderslice** [comment]
this looks good!

**Pull request merged**
